version: '3'

services:

  db:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_USER: bingo
      POSTGRES_PASSWORD: SecretSquirrel
    ports:
      - 5432:5432

  influxdb:
    image: influxdb:1.7.3
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: bingo
  
  chronograf:
    image: chronograf:1.7.5
    ports:
      - 8888:8888
    depends_on:
      - influxdb
    links:
      - influxdb
  
  grafana:
    image: grafana/grafana:5.3.2
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    links:
      - influxdb  
